#!/usr/bin/perl

use haruca;
use strict;

haruca::prt_logdate("SYS_WRITEFAIL START");
 

my ($hostname,$result,$date,$cmd,$options,$dir);
my ($startup,$running,$cmd_diff);


$dir = $0;
$dir =~ s/sys_//g;
system("rm -f $dir/*");

foreach $hostname (split(/\n/,`$main::config_haruca{'binpath'}search . -h`)){
  $hostname =~ s/\ +//g;


  $running = `$main::config_haruca{'binpath'}show run '$hostname'`;
  $startup = `$main::config_haruca{'binpath'}show start '$hostname'`;

  #print "CHECK $hostname : ";
  if(($running =~ /$main::config_haruca{'noinfo'}/) && ($startup =~ /$main::config_haruca{'noinfo'}/)){
      #print " SKIP\n";
      next;
  }
  #print " Diff Check\n";


  open(FILE,"> $main::config_haruca{'tmppath'}running");
  print FILE $running;
  close(FILE);
  
  open(FILE,"> $main::config_haruca{'tmppath'}startup");
  print FILE $startup;
  close(FILE);

  $cmd_diff  = " diff $main::config_haruca{'tmppath'}running $main::config_haruca{'tmppath'}startup | egrep '(^<|^>)' ";
  $cmd_diff .= " | egrep -v '(^[<>]\ *\$)'";
  $cmd_diff .= " | egrep -v '(^[<>]\ *show)'";
  $cmd_diff .= " | egrep -v '(^[<>]\ *Building)'";
  $cmd_diff .= " | egrep -v '(^[<>]\ *.+compressed)'";
  $cmd_diff .= " | egrep -v '(^[<>]\ *Current\ configuration)'";
  $cmd_diff .= " | egrep -v '(^[<>]\ *$hostname)'";
  $cmd_diff .= " | egrep -v '(#time|secret|community|snmp-server host|password|clock-period|authentication-key)'";
  $cmd_diff .= " | egrep -v '(Time source is NTP,|Load for five secs)'";
  $cmd_diff .= " | egrep -v '(^[<>]\ *\!|^[<>]\ *$main::config_haruca{'delim'}|Using..*out of..*bytes)'";
  $result = `$cmd_diff`;


  system("rm -f $main::config_haruca{'tmppath'}running $main::config_haruca{'tmppath'}startup ");
  if($result){
    $date = haruca::get_localtime();
    open(FILE,"> $dir/${hostname}-$date");
    print FILE $result;
    close(FILE);
  }

}


haruca::prt_logdate("SYS_WRITEFAIL END");


exit;
